### ISSUE TITLE
Gboard not all new emojis | iPhone8.4 iOS9.3.3 

### ISSUE THREAD

**Issue by mucke5** [PoomSmart/PoomSmart.github.io#1]
Hello. I appreciate your development getting all current emoticons on an older iOS.
In the normal keyboard, all emoticons are available and working fine.
When I am using the Gboard App as keyboard layout, not all current emoticons are shown. Could the Gboard have an internal restriction?
[https://itunes.apple.com/us/app/gboard-a-new-keyboard-from-google/id1091700242?mt=8](url)
If you need further information, let me know. Thanks in advance for helping me out.

**Comment by PoomSmart** [comment]
Has Gboard already been updated to support latest (10.2) emojis?

**Comment by mucke5** [comment]
Probably you are right. The Gboard needs an update.
[http://www.macworld.com/article/3173615/ios/google-updates-gboard-for-ios-with-new-emoji-and-voice-typing.html](url)
The latest (10.2) emojis are not listed.

**Comment by PoomSmart** [comment]
And adding new emojis to third-party keyboards is not of Emoji10's responsibility. Instead, a developer has to write a separate tweak to override their emojis list.
