### ISSUE TITLE
Update AdGuard Unbounded for iOS 15?

### ISSUE THREAD

**Issue by DetachHead** [PoomSmart/PoomSmart.github.io#11]
Sorry if this is the wrong place to ask but I couldn't find a repo for this tweak on your profile  

When I try to install it I get this error

![image](https://user-images.githubusercontent.com/57028336/206572896-1e34d40b-c9e8-47cf-95d4-f48a47a678e5.png)

**Comment by PoomSmart** [comment]
Retired.
