### ISSUE TITLE
Rootless package versions

### ISSUE THREAD

**Issue by jjolano** [PoomSmart/PoomSmart.github.io#14]
@PoomSmart 

The new rootless packages are causing issues for regular rooted jailbreaks' package managers - essentially it will always show that there is an update available for your packages, even if the user is to manually update to the regular updated version of that package.

The main reason why this is happening is because the dashed versions actually count as a higher version - and current package managers don't handle the new arch correctly when listing packages.

There are two solutions to this (assuming using the same repo and not a separate rootless repo):
- Use the same version number for both packages, and sort your Packages file in a way where iphoneos-arm packages are listed before iphoneos-arm64 packages.
- Use the tilde (~) instead of a dash (-), this will force APT to sort rootless versions as a lesser version than regular.

**Comment by PoomSmart** [comment]
Thanks for pointing out. I went with your second solution. 🫡
