### ISSUE TITLE
The name of repo disappeared 

### ISSUE THREAD

**Issue by NguyenASang** [PoomSmart/PoomSmart.github.io#8]
You can see in this picture:
![File_000](https://user-images.githubusercontent.com/87893636/149440490-d16e3c31-ad27-4ac8-9cec-0da0a42e188d.png)

### Moreover, Can I request you to make a tweak for iOS 12 ?? Thank you.

**Comment by PoomSmart** [comment]
- Something is wrong with your package manager. Try refreshing sources.
- To make things clear, I don't take tweak requests. I pick up ideas on my own.
