### ISSUE TITLE
Did you drop support for < 14 firmwares in terms of fonts?

### ISSUE THREAD

**Issue by foxnoodles** [PoomSmart/PoomSmart.github.io#9]
I only see ios 14 compatible emoji font on your repo. Are u dropping the support for lower firmwares?

**Comment by PoomSmart** [comment]
Done.

**Comment by foxnoodles** [comment]
Latest emoji-attributes crashes springboard on 10.3.3. I know I shouldn't be reporting it here. sorry about that

**Comment by PoomSmart** [comment]
@foxnoodles Look at your crash reporting tool and see which tweak is the culprit. Then file an issue to a corresponding project on my GitHub. That would help for resolution.
